// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/yp-metrics/internal/handlers/metric_get_body.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/yp-metrics/internal/types"
)

// MockMetricGetterBody is a mock of MetricGetterBody interface.
type MockMetricGetterBody struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetterBodyMockRecorder
}

// MockMetricGetterBodyMockRecorder is the mock recorder for MockMetricGetterBody.
type MockMetricGetterBodyMockRecorder struct {
	mock *MockMetricGetterBody
}

// NewMockMetricGetterBody creates a new mock instance.
func NewMockMetricGetterBody(ctrl *gomock.Controller) *MockMetricGetterBody {
	mock := &MockMetricGetterBody{ctrl: ctrl}
	mock.recorder = &MockMetricGetterBodyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetterBody) EXPECT() *MockMetricGetterBodyMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricGetterBody) Get(ctx context.Context, id types.MetricID) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricGetterBodyMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricGetterBody)(nil).Get), ctx, id)
}
